version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: ${GRAFANA_DOMAIN}
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:latest
    command:
      - "-config.file=/etc/loki/loki.yaml"
    volumes:
      - loki_data:/loki
    configs:
      - source: loki_config
        target: /etc/loki/loki.yaml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  tempo:
    image: grafana/tempo:latest
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    volumes:
      - tempo_data:/tempo
    configs:
      - source: tempo_config
        target: /etc/tempo/tempo.yaml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  alloy:
    image: grafana/alloy:latest
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    volumes:
      - alloy_data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: alloy_config
        target: /etc/alloy/config.alloy
    ports:
      - "127.0.0.1:12345:12345"
    networks:
      - platform_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

configs:
  grafana_datasources:
    file: ./grafana-datasources.yml
  prometheus_config:
    file: ./prometheus.yml
  loki_config:
    file: ./loki.yaml
  tempo_config:
    file: ./tempo.yaml
  alloy_config:
    file: ./alloy.river

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data:
  alloy_data:

networks:
  platform_net:
    external: true
    name: ${PLATFORM_NET_NAME}
