version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: ${GRAFANA_DOMAIN}
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:latest
    command:
      - "-config.file=/etc/loki/loki.yaml"
    volumes:
      - loki_data:/loki
    configs:
      - source: loki_config
        target: /etc/loki/loki.yaml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  tempo:
    image: grafana/tempo:latest
    user: "${TEMPO_UID:-0}"
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    volumes:
      - tempo_data:/var/lib/tempo
    configs:
      - source: tempo_config
        target: /etc/tempo/tempo.yaml
    networks:
      - platform_net
    deploy:
      restart_policy:
        condition: on-failure

  alloy:
    image: grafana/alloy:latest
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--server.http.ui-path-prefix=/alloy"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    environment:
      APP_ENV: ${APP_ENV:-dev}
    volumes:
      - alloy_data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: alloy_config
        target: /etc/alloy/config.alloy
    networks:
      - platform_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

configs:
  grafana_datasources:
    file: ${OBSERVABILITY_DIR:?OBSERVABILITY_DIR is required}/grafana-datasources.yml
    name: ${STACK_NAME:?STACK_NAME is required}_grafana_datasources_${CONFIG_VERSION:?CONFIG_VERSION is required}
  prometheus_config:
    file: ${OBSERVABILITY_DIR:?OBSERVABILITY_DIR is required}/prometheus.yml
    name: ${STACK_NAME:?STACK_NAME is required}_prometheus_config_${CONFIG_VERSION:?CONFIG_VERSION is required}
  loki_config:
    file: ${OBSERVABILITY_DIR:?OBSERVABILITY_DIR is required}/loki.yaml
    name: ${STACK_NAME:?STACK_NAME is required}_loki_config_${CONFIG_VERSION:?CONFIG_VERSION is required}
  tempo_config:
    file: ${OBSERVABILITY_DIR:?OBSERVABILITY_DIR is required}/tempo.yaml
    name: ${STACK_NAME:?STACK_NAME is required}_tempo_config_${CONFIG_VERSION:?CONFIG_VERSION is required}
  alloy_config:
    file: ${OBSERVABILITY_DIR:?OBSERVABILITY_DIR is required}/alloy.river
    name: ${STACK_NAME:?STACK_NAME is required}_alloy_config_${CONFIG_VERSION:?CONFIG_VERSION is required}

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data:
  alloy_data:

networks:
  platform_net:
    external: true
    name: ${PLATFORM_NET_NAME}
